### ISSUE TITLE
`grunt release` does not create CHANGELOG, tag (locally), does not update bower.json / package.json and does not commit, does not set note on GitHub release

### ISSUE THREAD

**Issue by gr2m** [boennemann/grunt-semantic-release#6]
Tested with https://github.com/gr2m/release-test

here is what I get in the console

``` bash
$ grunt release
Running "release" task
>> Latest tags pulled.
[?] What kind of changes did you make? fixes

Running "bump:patch" (bump) task
>> Version bumped to 0.0.1
>> Tagged as "release-v0.0.1"
>> Pushed to origin master

Running "set-tag" task

Running "git-delete-tag:local" (git-delete-tag) task

Running "reset-package" task

Done, without errors.
```

Here is the build on Travis:
https://travis-ci.org/gr2m/release-test/builds/34322869

Here is the release on GItHub:
https://github.com/gr2m/release-test/releases/tag/release-v0.0.1

I guess I did something wrong?

**Comment by gr2m** [comment]
btw feel free to mess with https://github.com/gr2m/release-test, I've added you as collaborator

**Comment by boennemann** [comment]
The local `grunt release` isn't supposed to create these things yet. So it works as expected.
But due to #5 your `.travis.yml` isn't configured correctly. Try removing it and running the setup script with  the new `0.2.1` again.

This is how things are supposed to work
![grunt-semantic-release 02](https://cloud.githubusercontent.com/assets/908178/4162089/e8dfebf0-34d6-11e4-840e-6a4faf7ab7ae.gif)
